### PR TITLE
Add additional validation to various forms

### LINKED ISSUE #441: Add Validation to Section Creation window
Scheduler crashes in coord side when creating a section without a location. Make validation check in front end before making API request to back end. 

image
image

### PR DESCRIPTION
**Pull request by smartspot2**
Resolves #441

The section creation form and the override creation form have been causing several errors in the backend, since there is no input validation in the frontend. These forms have now been updated to provide input validation, displayed to the user upon clicking the save/submit button.

### CODE REVIEW

**Review by edwardneo — APPROVED** [review]
LGTM!

**Review by jacovkim — DISMISSED** [review]
looks good!

**Review by jacovkim — APPROVED** [review]
Looks good to me!

**Review by jacovkim — DISMISSED** [review]
Looks good to me!

**Review by edwardneo — DISMISSED** [review]
LGTM!

**Review by jacovkim — CHANGES_REQUESTED** [review]
Creating a section with space in Location field fails. Setting capacity to -1 also fails. Both  when creating a section or editing an existing section

**Review by jacovkim — APPROVED** [review]
LOOKS GOOD TO ME!

**Review by edwardneo — APPROVED** [review]
ALSO LOOKS GOOD TO ME!

**Pull request merged**
