### PR TITLE
Fix regression preventing students from dropping sections, add placeholder for mentor page

### PR DESCRIPTION
**Pull request by Svetlitski**

### CODE REVIEW

**Comment by Svetlitski** [comment]
Checks are not passing because of all the unused variables due to me commenting out most of `<MentorSection>`, so just ignore that.

**Comment by noloerino** [comment]
student card needs to be updated to display both spacetimes if multiple to avoid confusing people (since that's their primary source of truth once they've hit enroll) - otherwise lgtm

**Comment by Svetlitski** [comment]
> student card needs to be updated to display both spacetimes if multiple to avoid confusing people (since that's their primary source of truth once they've hit enroll) - otherwise lgtm

@noloerino It already does that, are you not seeing it locally?
Screen Shot 2020-09-08 at 10 56 34 PM

**Comment by noloerino** [comment]
oh I actually am, my brain just got confused because I thought the middle card was for something else - it's not the greatest design, but it works for now

**Pull request merged**
